### ISSUE TITLE
how to fix the problem ? could you please provide  a step by step  document.

### ISSUE THREAD

**Issue by ChainCoderX** [desmos-labs/mooncake#152]
(base) adeMacBook-Pro:mooncake a$ flutter run
Using hardware rendering with device sdk gphone x86. If you notice graphics artifacts, consider enabling software
rendering with "--enable-software-rendering".
Launching lib/main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
File google-services.json is missing. The Google Services Plugin cannot function without it.
Searched Location:
/Users/a/go/src/github.com/desmos-labs/mooncake/android/app/src/nullnull/google-services.json
/Users/a/go/src/github.com/desmos-labs/mooncake/android/app/src/debug/google-services.json
/Users/a/go/src/github.com/desmos-labs/mooncake/android/app/src/nullnullDebug/google-services.json
/Users/a/go/src/github.com/desmos-labs/mooncake/android/app/src/nullnull/debug/google-services.json
/Users/a/go/src/github.com/desmos-labs/mooncake/android/app/src/debug/nullnull/google-services.json
/Users/a/go/src/github.com/desmos-labs/mooncake/android/app/google-services.json

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 15m 3s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done 904.7s (!)
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by ChainCoderX** [comment]
https://github.com/flutter/flutter/issues/65687

**Comment by rmontagnin** [comment]
Hello @wade-liwei. Unfortunately, right now Mooncake requires a `google-play-services.json` file in order to work properly. This is due to the fact that we're using the Firebase Cloud Messaging service to send to the application push notifications. 

In order to solve your issue you can: 

1. Setup a free Firebase project using the [Firebase Cloud Console](https://console.firebase.google.com/u/0/?pli=1). 
2. Add an Android app to your project. 
3. Download the generated `google-services.json` file. 
4. Place such file inside the `android/app` folder of the Mooncake project. 

Once you have done so, you will be able to run the project properly.
