### ISSUE TITLE
Edit or remove the messages not committed

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/mooncake#55]
When there is one failed message, all messages be trying to broadcast after it will not be committed. It is because all the messages will be grouped together and sent as a single transaction. The `ValidateBasic` will already blocked the tx being delivered. This can be solved if we can remove any failed messages or edit the message to become the correct format.

**Comment by ryuash** [comment]
@kwunyeung @RiccardoM 
What do you guys think if we...
- Grab all the failed posts locally and list them at the top of the posts list so that we let the user know this is first priority (I don't know if that's what we currently do)
- When we sync the post we won't grabbed the error ones.
- Instead, we can have a `retry`, `delete` button (ok an`edit` too but I would prioritize the `retry` and `delete`) that would allow the user to reset the post status for syncing or remove it locally.

**Comment by kwunyeung** [comment]
This sounds a good approach. This is similar to the users Flow of Instagram. They have a small preview of failed post and as users to `retry` or `delete`. 

<img src="https://user-images.githubusercontent.com/932636/90356491-47037280-e082-11ea-9d2d-4a23115d88a8.png" width="200" /> <img src="https://user-images.githubusercontent.com/932636/90356566-8e89fe80-e082-11ea-897b-87535011bd33.png" width="200" />

They also put those not posted post in `Draft`. When you create a new post, it shows those `drafts`.

<img src="https://user-images.githubusercontent.com/932636/90356528-64384100-e082-11ea-82e6-3d314ed29811.png" width="200" />

**Comment by rmontagnin** [comment]
I approve your proposal @ryuash
