### ISSUE TITLE
Apple devices not receiving push notifications

### ISSUE THREAD

**Issue by rmontagnin** [desmos-labs/mooncake#80]
## Generic information
- OS name and version: iOS
- Application build code: `4102` 
- Network type (mobile/Wi-Fi): Both 

## Bug description
While inside Android everything works properly, iOS devices do not receive the proper push notifications. 

## Steps to reproduce
1. Create a post. 
2. Ask someone to like it. 

## Expected behavior
You should receive a push notifications telling someone has liked the post, but nothing happens.

**Comment by kwunyeung** [comment]
Even I have created an APN key on **Apple** and added it to **Firebase**, I still don't receive any notifications. @bragaz please see if there is any other setup we need to do besides only adding the key. Thanks!

**Comment by leobragaz** [comment]
I will take a look at it asap as it's become an obesession for me right now! I think we're close to a solution. @kwunyeung

**Comment by leobragaz** [comment]
As stated by @lauranori today, on `0.4.2` notifications are working fine with both app in background or killed on iOS `13.5.1`.
The problem was that we didn't upload the APN key inside the `Cloud Messaging` section of Firebase.
Also, before `0.4.1` we didn't check two options inside the `signing and capabilities` which were the following ones:
<img width="532" alt="Schermata 2020-08-03 alle 13 58 41" src="https://user-images.githubusercontent.com/26248202/89180152-72ba2f00-d591-11ea-8b60-c565698c40a1.png">

I've checked that we've followed every point of [this guide](https://devspush.com/blog/3-how-to-configure-push-notifications-with-flutter
) and I can confirm that we did!
